server:
  port: 4004

spring:
  application:
    name: api-gateway
  #Config server
  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      routes:
        ### http://localhost:4004/auth/login
        ### API GATEWAY -> http://auth-service:4005/login
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        ### REST CLIENT -> http://localhost:4004/api/patients
        ### API GATEWAY -> http://patient-service:4000
        ### PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/patients, /api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        ### REST CLIENT -> http://localhost:4004/api-docs
        ### API GATEWAY -> http://patient-service:4000
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

# JWT Configuration - THIS IS THE USUAL CULPRIT
jwt:
  # MUST BE AT LEAST 32 CHARACTERS (256-bit)
  secret: "9a4f2c8d3b7a1e6f5d8c3a2b1e6f5d8c3a2b1e6f5d8c3a2b1e6f5d8c3a2b1e6f"
  expiration: 86400000

eureka:
#  instance:
#    # This is the most important setting for Docker
#    prefer-ip-address: true
#    # Optional: Ensure the ID is unique so Eureka doesn't get confused
#    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-reg:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0  # Send 100% of traces
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

auth-service:
  url: http://auth-service:4005
