spring.application.name=patient-service
server.port=4000

#Config server
spring.config.import=optional:configserver:http://config-server:8888

spring.datasource.embedded-database-connection=none

spring.datasource.url=jdbc:postgresql://patient-db:5433/patient_db
spring.datasource.username=postgres
spring.datasource.password=password

#spring.main.allow-bean-definition-overriding=true

#Eureka
eureka.client.serviceUrl.defaultZone=http://service-reg:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Zipkin
# 1. Sampling (1.0 = 100%)
management.tracing.sampling.probability=1.0
# 2. Zipkin Endpoint (Correct nesting for 3.2.x)
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
# 3. Actuator Exposure (Must include 'management' prefix)
#management.endpoints.web.exposure.include=health
#management.endpoints.health.show-details=always

#Resilience4J
# Monitoring & Health
resilience4j.circuitbreaker.instances.patientBreaker.registerHealthIndicator=true

# Window Settings
# Last 10 calls recorded
resilience4j.circuitbreaker.instances.patientBreaker.slidingWindowSize=10
# Can be COUNT_BASED or TIME_BASED
resilience4j.circuitbreaker.instances.patientBreaker.slidingWindowType=COUNT_BASED
# Min calls required before calculating error rate
resilience4j.circuitbreaker.instances.patientBreaker.minimumNumberOfCalls=5

# Thresholds
# Opens if 50% of calls fail
resilience4j.circuitbreaker.instances.patientBreaker.failureRateThreshold=50
# Opens if 100% of calls are slower than duration
resilience4j.circuitbreaker.instances.patientBreaker.slowCallRateThreshold=100
# Calls taking > 2s are considered "slow"
resilience4j.circuitbreaker.instances.patientBreaker.slowCallDurationThreshold=2s

# State Transitions
# Wait 10s before trying again (Half-Open)
resilience4j.circuitbreaker.instances.patientBreaker.waitDurationInOpenState=10s
# 3 calls allowed to test if service is back
resilience4j.circuitbreaker.instances.patientBreaker.permittedNumberOfCallsInHalfOpenState=3

# Exception Handling
# Which exceptions count as failure
resilience4j.circuitbreaker.instances.patientBreaker.recordExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.circuitbreaker.instances.patientBreaker.recordExceptions[1]=java.io.IOException

# Which exceptions should NOT trip the breaker
resilience4j.circuitbreaker.instances.ignoreExceptions[0]=com.pm.exception.PatientNotFoundException

# Actuator configuration
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest