spring.application.name=auth-service
server.port=4005

spring.datasource.embedded-database-connection=none

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=password

jwt.secret=9a4f2c8d3b7a1e6f5d8c3a2b1e6f5d8c3a2b1e6f5d8c3a2b1e6f5d8c3a2b1e6f

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Config server
#spring.profiles.active=dev
spring.config.import=optional:configserver:http://localhost:8888

#Resilience4J
# Monitoring & Health
resilience4j.circuitbreaker.instances.authBreaker.registerHealthIndicator=true

# Window Settings
# Last 10 calls recorded
resilience4j.circuitbreaker.instances.authBreaker.slidingWindowSize=10
# Can be COUNT_BASED or TIME_BASED
resilience4j.circuitbreaker.instances.authBreaker.slidingWindowType=COUNT_BASED
# Min calls required before calculating error rate
resilience4j.circuitbreaker.instances.authBreaker.minimumNumberOfCalls=5

# Thresholds
# Opens if 50% of calls fail
resilience4j.circuitbreaker.instances.authBreaker.failureRateThreshold=50
# Opens if 100% of calls are slower than duration
resilience4j.circuitbreaker.instances.authBreaker.slowCallRateThreshold=100
# Calls taking > 2s are considered "slow"
resilience4j.circuitbreaker.instances.authBreaker.slowCallDurationThreshold=2s

# State Transitions
# Wait 10s before trying again (Half-Open)
resilience4j.circuitbreaker.instances.authBreaker.waitDurationInOpenState=10s
# 3 calls allowed to test if service is back
resilience4j.circuitbreaker.instances.authBreaker.permittedNumberOfCallsInHalfOpenState=3

# Exception Handling
# Which exceptions count as failure
resilience4j.circuitbreaker.instances.authBreaker.recordExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.circuitbreaker.instances.authBreaker.recordExceptions[1]=java.io.IOException

# Which exceptions should NOT trip the breaker
resilience4j.circuitbreaker.instances.ignoreExceptions[0]=com.pm.exception.PatientNotFoundException

# Actuator configuration
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always