services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      CLUSTER_ID: '5L6g3nShT-eMCtK--X86sw'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9094:9094"
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 5

  patient-db:
    image: postgres:15-alpine
    container_name: patient-db
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-volumes/patient-db:/var/lib/postgresql/data
      - ./patient-service/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d patient_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-volumes/auth-db:/var/lib/postgresql/data
      - ./auth-service/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  service-reg:
    image: markcus0526/service-reg:latest
    container_name: service-reg
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s

  config-server:
    image: markcus0526/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - app-network
    depends_on:
      service-reg:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: "true" # Forces clone during healthcheck period
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s # Wait 1 full minute before the FIRST check

  api-gateway:
    image: markcus0526/api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"

  auth-service:
    image: markcus0526/auth-service:latest
    container_name: auth-service
    ports:
      - "4005:4005"
    depends_on:
      auth-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"

  analytics-service:
    image: markcus0526/analytics-service:latest
    container_name: analytics-service
    ports:
      - "4003:4003"
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"

  billing-service:
    image: markcus0526/billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"

  patient-service:
    image: markcus0526/patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      config-server:
        condition: service_healthy
      patient-db:
        condition: service_healthy
      kafka:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"

networks:
  app-network:
    driver: bridge

volumes:
  patient-db:
  auth-db:
