server:
  port: 4004

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        ### http://localhost:4004/auth/login
        ### API GATEWAY -> http://auth-service:4005/login
        - id: auth-service
          uri: http://localhost:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        ### REST CLIENT -> http://localhost:4004/api/patients
        ### API GATEWAY -> http://patient-service:4000
        ### PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array
        - id: patient-service
          uri: http://localhost:4000
          predicates:
            - Path=/api/patients, /api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        ### REST CLIENT -> http://localhost:4004/api-docs
        ### API GATEWAY -> http://patient-service:4000
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

auth:
  service:
    url: http://localhost:4005 # Or whatever your auth-service URL is

# JWT Configuration - THIS IS THE USUAL CULPRIT
jwt:
  # MUST BE AT LEAST 32 CHARACTERS (256-bit)
  secret: "9a4f2c8d3b7a1e6f5d8c3a2b1e6f5d8c3a2b1e6f5d8c3a2b1e6f5d8c3a2b1e6f"
  expiration: 86400000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/