spring.application.name=patient-service
server.port=4000

spring.datasource.embedded-database-connection=none

spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.main.allow-bean-definition-overriding=true

#Eureka
eureka.client.serviceUrl.default=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Zipkin
# 1. Sampling (1.0 = 100%)
management.tracing.sampling.probability=1.0
# 2. Zipkin Endpoint (Correct nesting for 3.2.x)
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
# 3. Actuator Exposure (Must include 'management' prefix)
management.endpoints.web.exposure.include=health,info,tracing

#Config server
spring.config.import=optional:configserver:http://localhost:8888
#spring.profiles.active=dev