spring.application.name=analytics-service
server.port=4003

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=analytics-service-v1
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

logging.level.org.springframework.kafka=INFO
spring.kafka.properties.request.timeout.ms=30000

spring.main.allow-bean-definition-overriding=true

eureka.client.serviceUrl.defaultZone=http://service-reg:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Config server
spring.config.import=optional:configserver:http://config-server:8888
#spring.profiles.active=dev

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest