spring.application.name=config-server
server.port=4006

spring.main.allow-bean-definition-overriding=true

eureka.client.serviceUrl.default=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.server.git.uri=https://github.com/Markcus0526/mark-patient-spring-boot-cloud/config-server//application.properties