spring.application.name=config-server
server.port=8888

logging.level.org.springframework.cloud.config.server=DEBUG

spring.main.allow-bean-definition-overriding=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#spring.cloud.config.server.git.uri=https://github.com/Markcus0526/mark-patient-spring-boot-cloud/blob/main/application-config
# 1. The URI must be the base Repository URL
spring.cloud.config.server.git.uri=https://github.com/Markcus0526/mark-patient-spring-boot-cloud

# 2. Tell the server to look inside your subfolder
spring.cloud.config.server.git.search-paths=application-config

# 3. Explicitly set the branch (GitHub defaults to 'main' now)
spring.cloud.config.server.git.default-label=main

# 4. Use a clean base directory to clear the previous "Invalid remote" error
#spring.cloud.config.server.git.basedir=Markcus0526/mark-patient-spring-boot-cloud